language: java
jdk:
- oraclejdk8
before_install:
- openssl aes-256-cbc -K $encrypted_c4a4dd5eee87_key -iv $encrypted_c4a4dd5eee87_iv
  -in src/main/resources/application.properties.enc -out src/main/resources/application.properties -d

